spring:
  datasource:
    username: Alex
    password: Alex
    url: jdbc:postgresql://localhost:5432/auto
    hikari:
      schema: shop

  flyway:
    baseline-on-migrate: true
    schemas: shop

server:
  port: 8081

autocatalogapi:
  feign:
    name: autoCatalogApi
    url: http://localhost:8080